version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"  
    environment:
      REACT_APP_API_URL: "${REACT_APP_API_URL}"
      REACT_APP_API_KEY: "${REACT_APP_API_KEY}"

volumes:
  postgres-data:
